<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="10" total="16" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Suite" duration-ms="68716" started-at="2021-11-14T05:21:13Z" finished-at="2021-11-14T05:22:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="68716" started-at="2021-11-14T05:21:13Z" finished-at="2021-11-14T05:22:22Z">
      <class name="testCases.LoginToMyStore">
        <test-method status="PASS" signature="initialization()[pri:0, instance:testCases.LoginToMyStore@57fffcd7]" name="initialization" is-config="true" duration-ms="1072" started-at="2021-11-14T05:21:12Z" finished-at="2021-11-14T05:21:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="getTestCaseName()[pri:0, instance:testCases.LoginToMyStore@57fffcd7]" name="getTestCaseName" is-config="true" duration-ms="4" started-at="2021-11-14T05:21:13Z" finished-at="2021-11-14T05:21:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="loginToMyStore(java.util.Hashtable)[pri:0, instance:testCases.LoginToMyStore@57fffcd7]" name="loginToMyStore" duration-ms="24674" started-at="2021-11-14T05:21:13Z" data-provider="data_Collection" finished-at="2021-11-14T05:21:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Page_Title=My Store, Contact_No=123456789, Email_ID=testwrwrw2342342@gmail.com, Password=pass123, Sr.No=1, City=Pune, First_Name=Abhishek, Last_Name=xyzdd}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:testCases.LoginToMyStore@57fffcd7]" name="endTest" is-config="true" duration-ms="798" started-at="2021-11-14T05:22:22Z" finished-at="2021-11-14T05:22:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- testCases.LoginToMyStore -->
      <class name="testCases.LoginToMyStoreWithRegisteredUser">
        <test-method status="PASS" signature="getTestCaseName()[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser@598067a5]" name="getTestCaseName" is-config="true" duration-ms="3" started-at="2021-11-14T05:21:38Z" finished-at="2021-11-14T05:21:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="loginToMyStoreWithRegisteredUser(java.util.Hashtable)[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser@598067a5]" name="loginToMyStoreWithRegisteredUser" duration-ms="22132" started-at="2021-11-14T05:21:38Z" data-provider="data_Collection" finished-at="2021-11-14T05:22:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Page_Title=My Store, Contact_No=234567894, Email_ID=testHemPrabha@gmail.com, Password=pass126, Sr.No=1, City=Delhi, First_Name=HemPrabha, Last_Name=last Name}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStoreWithRegisteredUser -->
      </class> <!-- testCases.LoginToMyStoreWithRegisteredUser -->
      <class name="testCases.LoginToMyStoreWithRegisteredUser3">
        <test-method status="SKIP" signature="getTestCaseName()[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser3@14bf9759]" name="getTestCaseName" is-config="true" duration-ms="1" started-at="2021-11-14T05:22:00Z" finished-at="2021-11-14T05:22:00Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser3]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser3
at testCases.LoginToMyStoreWithRegisteredUser3.getTestCaseName(LoginToMyStoreWithRegisteredUser3.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="SKIP" signature="loginToMyStoreWithRegisteredUser3(java.util.Hashtable)[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser3@14bf9759]" name="loginToMyStoreWithRegisteredUser3" duration-ms="0" started-at="2021-11-14T05:22:00Z" data-provider="data_Collection" finished-at="2021-11-14T05:22:00Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser3]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser3
at testCases.LoginToMyStoreWithRegisteredUser3.getTestCaseName(LoginToMyStoreWithRegisteredUser3.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStoreWithRegisteredUser3 -->
      </class> <!-- testCases.LoginToMyStoreWithRegisteredUser3 -->
      <class name="testCases.LoginToMyStore2">
        <test-method status="SKIP" signature="getTestCaseName()[pri:0, instance:testCases.LoginToMyStore2@31ef45e3]" name="getTestCaseName" is-config="true" duration-ms="1" started-at="2021-11-14T05:21:38Z" finished-at="2021-11-14T05:21:38Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStore2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStore2
at testCases.LoginToMyStore2.getTestCaseName(LoginToMyStore2.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="SKIP" signature="loginToMyStore2(java.util.Hashtable)[pri:0, instance:testCases.LoginToMyStore2@31ef45e3]" name="loginToMyStore2" duration-ms="0" started-at="2021-11-14T05:21:38Z" data-provider="data_Collection" finished-at="2021-11-14T05:21:38Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStore2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStore2
at testCases.LoginToMyStore2.getTestCaseName(LoginToMyStore2.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore2 -->
      </class> <!-- testCases.LoginToMyStore2 -->
      <class name="testCases.EndToEndTestCase">
        <test-method status="PASS" signature="getTestCaseName()[pri:0, instance:testCases.EndToEndTestCase@5f341870]" name="getTestCaseName" is-config="true" duration-ms="1" started-at="2021-11-14T05:22:00Z" finished-at="2021-11-14T05:22:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="FAIL" signature="endToEndTestCase(java.util.Hashtable)[pri:0, instance:testCases.EndToEndTestCase@5f341870]" name="endToEndTestCase" duration-ms="20746" started-at="2021-11-14T05:22:00Z" data-provider="data_Collection" finished-at="2021-11-14T05:22:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Page_Title=My Store, Contact_No=123456789, Email_ID=testMayuri@gmail.com, Password=pass125, Sr.No=1.0, City=Nagpur, First_Name=EndToEnd, Last_Name=Test Case}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Store] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Store] but found [Login - My Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at utility.CommonMethods.verifyPageTitle(CommonMethods.java:60)
at pages.HomePage.LoginWithRegisteredUser(HomePage.java:25)
at testCases.EndToEndTestCase.endToEndTestCase(EndToEndTestCase.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endToEndTestCase -->
      </class> <!-- testCases.EndToEndTestCase -->
      <class name="testCases.LoginToMyStoreWithRegisteredUser2">
        <test-method status="SKIP" signature="getTestCaseName()[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser2@3c0ecd4b]" name="getTestCaseName" is-config="true" duration-ms="1" started-at="2021-11-14T05:22:00Z" finished-at="2021-11-14T05:22:00Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser2
at testCases.LoginToMyStoreWithRegisteredUser2.getTestCaseName(LoginToMyStoreWithRegisteredUser2.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="SKIP" signature="loginToMyStoreWithRegisteredUser2(java.util.Hashtable)[pri:0, instance:testCases.LoginToMyStoreWithRegisteredUser2@3c0ecd4b]" name="loginToMyStoreWithRegisteredUser2" duration-ms="0" started-at="2021-11-14T05:22:00Z" data-provider="data_Collection" finished-at="2021-11-14T05:22:00Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to No for Test case: LoginToMyStoreWithRegisteredUser2
at testCases.LoginToMyStoreWithRegisteredUser2.getTestCaseName(LoginToMyStoreWithRegisteredUser2.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStoreWithRegisteredUser2 -->
      </class> <!-- testCases.LoginToMyStoreWithRegisteredUser2 -->
    </test> <!-- Test -->
  </suite> <!-- Regression Suite -->
</testng-results>
